# Generated by Django 2.0.8 on 2019-04-06 22:12

import blog.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_thumbs.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('title', models.CharField(max_length=255, verbose_name='Название Галереи')),
                ('slug', models.SlugField(editable=False, max_length=160, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Галереи',
                'verbose_name': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Оглавление категории')),
            ],
            options={
                'verbose_name_plural': 'Категории галерей',
                'verbose_name': 'Категория галереи',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_thumbs.fields.ImageThumbsField(help_text='Файл фотографии для галереи', sizes=({'code': 'thumb', 'resize': 'crop', 'wxh': '500x500'}, {'code': 'bigthumb', 'resize': 'crop', 'wxh': '1000x1000'}), upload_to=blog.models.get_file_path)),
                ('title', models.CharField(default='', max_length=255, verbose_name='Оглавление фотографии')),
                ('description', models.TextField(default='', verbose_name='Описание фотографии')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.Gallery', verbose_name='Галерея')),
            ],
            options={
                'verbose_name_plural': 'Фотографии в галерее',
                'verbose_name': 'Фотография в галерее',
            },
        ),
        migrations.CreateModel(
            name='PostFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(blank=True, null=True, upload_to=blog.models.get_file_path_blog, verbose_name='Прикрепленный Файл')),
                ('description', models.CharField(max_length=300, verbose_name='Описание Файла')),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_thumbs.fields.ImageThumbsField(sizes=({'code': 'thumb', 'resize': 'crop', 'wxh': '750x400'},), upload_to=blog.models.get_file_path_blog)),
                ('description', models.CharField(blank=True, default='', max_length=300, verbose_name='Описание изображения')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок Новости', max_length=400, verbose_name='Заголовок')),
                ('abstract', models.TextField(blank=True, help_text='Короткая аннотация для баннера на главной', verbose_name='Аннотация')),
                ('body', tinymce.models.HTMLField(help_text='Текст Новости', verbose_name='Текст')),
                ('date', models.DateField(default=datetime.datetime.now, help_text='Дата Новости', null=True, verbose_name='Дата')),
                ('category', models.CharField(choices=[('ПОДІЇ', 'ПОДІЇ'), ("МІЖНАРОДНІ ЗВ'ЯЗКИ", "МІЖНАРОДНІ ЗВ'ЯЗКИ"), ('СТАТТІ', 'СТАТТІ'), ('СТУДЕНТСЬКЕ ЖИТТЯ', 'СТУДЕНТСЬКЕ ЖИТТЯ')], default='ПОДІЇ', help_text='Категория Новости', max_length=19, verbose_name='Категория')),
                ('newsfeed', django_thumbs.fields.ImageThumbsField(help_text='Изображение для Новости на главной ! ДОЛЖНО БЫТЬ 16:9 !', sizes=({'code': 'banner', 'resize': 'scale', 'wxh': '1024x576'},), upload_to=blog.models.get_file_path_blog)),
                ('slug', models.SlugField(editable=False, max_length=160, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Новости',
                'verbose_name': 'Новость',
            },
        ),
        migrations.AddField(
            model_name='postimage',
            name='posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.Posts', verbose_name='Посты'),
        ),
        migrations.AddField(
            model_name='postfile',
            name='posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='blog.Posts', verbose_name='Посты'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gals', to='blog.GalleryCategory', verbose_name='Категория'),
        ),
    ]
