# Generated by Django 2.0.8 on 2019-06-27 12:52

import blog.models
import datetime
from django.db import migrations, models
import django_thumbs.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsEng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок Новости', max_length=400, verbose_name='Заголовок')),
                ('abstract', models.TextField(blank=True, help_text='Короткая аннотация для баннера на главной', verbose_name='Аннотация')),
                ('body', tinymce.models.HTMLField(help_text='Текст Новости', verbose_name='Текст')),
                ('date', models.DateField(default=datetime.datetime.now, help_text='Дата Новости', null=True, verbose_name='Дата')),
                ('category', models.CharField(choices=[('ПОДІЇ', 'ПОДІЇ'), ("МІЖНАРОДНІ ЗВ'ЯЗКИ", "МІЖНАРОДНІ ЗВ'ЯЗКИ"), ('СТАТТІ', 'СТАТТІ'), ('СТУДЕНТСЬКЕ ЖИТТЯ', 'СТУДЕНТСЬКЕ ЖИТТЯ')], default='ПОДІЇ', help_text='Категория Новости', max_length=19, verbose_name='Категория')),
                ('newsfeed', django_thumbs.fields.ImageThumbsField(help_text='Изображение для Новости на главной ! ДОЛЖНО БЫТЬ 16:9 !', sizes=({'code': 'banner', 'resize': 'scale', 'wxh': '1024x576'},), upload_to=blog.models.get_file_path_blog)),
                ('slug', models.SlugField(editable=False, max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='PostsRus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок Новости', max_length=400, verbose_name='Заголовок')),
                ('abstract', models.TextField(blank=True, help_text='Короткая аннотация для баннера на главной', verbose_name='Аннотация')),
                ('body', tinymce.models.HTMLField(help_text='Текст Новости', verbose_name='Текст')),
                ('date', models.DateField(default=datetime.datetime.now, help_text='Дата Новости', null=True, verbose_name='Дата')),
                ('category', models.CharField(choices=[('ПОДІЇ', 'ПОДІЇ'), ("МІЖНАРОДНІ ЗВ'ЯЗКИ", "МІЖНАРОДНІ ЗВ'ЯЗКИ"), ('СТАТТІ', 'СТАТТІ'), ('СТУДЕНТСЬКЕ ЖИТТЯ', 'СТУДЕНТСЬКЕ ЖИТТЯ')], default='ПОДІЇ', help_text='Категория Новости', max_length=19, verbose_name='Категория')),
                ('newsfeed', django_thumbs.fields.ImageThumbsField(help_text='Изображение для Новости на главной ! ДОЛЖНО БЫТЬ 16:9 !', sizes=({'code': 'banner', 'resize': 'scale', 'wxh': '1024x576'},), upload_to=blog.models.get_file_path_blog)),
                ('slug', models.SlugField(editable=False, max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
