# Generated by Django 2.0.8 on 2019-06-27 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postseng_postsrus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postseng',
            options={'verbose_name': 'Английская Новость', 'verbose_name_plural': 'Английские Новости'},
        ),
        migrations.AlterModelOptions(
            name='postsrus',
            options={'verbose_name': 'Русская Новость', 'verbose_name_plural': 'Русские Новости'},
        ),
    ]
