# Generated by Django 2.0.8 on 2019-06-27 13:29

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190627_1556'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostsEng',
        ),
        migrations.DeleteModel(
            name='PostsRus',
        ),
        migrations.AddField(
            model_name='posts',
            name='enabstract',
            field=models.TextField(blank=True, default=models.TextField(blank=True, help_text='Аннотация для баннера на главной', verbose_name='Аннотация'), help_text='Английская аннотация для баннера на главной', verbose_name='Аннотация'),
        ),
        migrations.AddField(
            model_name='posts',
            name='enbody',
            field=tinymce.models.HTMLField(default=tinymce.models.HTMLField(help_text='Текст Новости', verbose_name='Текст'), help_text='Английский Текст Новости', verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='posts',
            name='entitle',
            field=models.CharField(default=models.CharField(help_text='Заголовок Новости', max_length=400, verbose_name='Заголовок'), help_text='Английский заголовок Новости', max_length=400, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='posts',
            name='ruabstract',
            field=models.TextField(blank=True, default=models.TextField(blank=True, help_text='Аннотация для баннера на главной', verbose_name='Аннотация'), help_text='Русская аннотация для баннера на главной', verbose_name='Аннотация'),
        ),
        migrations.AddField(
            model_name='posts',
            name='rubody',
            field=tinymce.models.HTMLField(default=tinymce.models.HTMLField(help_text='Текст Новости', verbose_name='Текст'), help_text='Русский Текст Новости', verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='posts',
            name='rutitle',
            field=models.CharField(default=models.CharField(help_text='Заголовок Новости', max_length=400, verbose_name='Заголовок'), help_text='Русский заголовок Новости', max_length=400, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='abstract',
            field=models.TextField(blank=True, help_text='Аннотация для баннера на главной', verbose_name='Аннотация'),
        ),
    ]
