# Generated by Django 2.0.8 on 2019-06-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190627_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='en',
            field=models.BooleanField(default=False, help_text='Новость на английском', verbose_name='Английская версия есть'),
        ),
        migrations.AddField(
            model_name='posts',
            name='ru',
            field=models.BooleanField(default=False, help_text='Новость на русском', verbose_name='Русская версия есть'),
        ),
    ]
