# Generated by Django 2.0.8 on 2019-07-21 18:35

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190627_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='enabstract',
            field=models.TextField(blank=True, help_text='Английская аннотация для баннера на главной', verbose_name='Английская Аннотация'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='enbody',
            field=tinymce.models.HTMLField(blank=True, help_text='Английский Текст Новости', verbose_name='Английский Текст'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='entitle',
            field=models.CharField(blank=True, help_text='Английский заголовок Новости', max_length=400, verbose_name='Английский Заголовок'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='ruabstract',
            field=models.TextField(blank=True, help_text='Русская аннотация для баннера на главной', verbose_name='Русская Аннотация'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='rubody',
            field=tinymce.models.HTMLField(blank=True, help_text='Русский Текст Новости', verbose_name='Русский Текст'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='rutitle',
            field=models.CharField(blank=True, help_text='Русский заголовок Новости', max_length=400, verbose_name='Русский Заголовок'),
        ),
    ]
