# Generated by Django 2.0.8 on 2020-02-29 11:33

import blog.models
from django.db import migrations, models
import django.db.models.deletion
import django_thumbs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190721_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('title', models.CharField(max_length=255, verbose_name='Название Музея')),
                ('slug', models.SlugField(editable=False, max_length=160, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Музеи',
                'verbose_name': 'Музей',
            },
        ),
        migrations.CreateModel(
            name='MuseumImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_thumbs.fields.ImageThumbsField(help_text='Файл фотографии экспоната', sizes=({'code': 'thumb', 'resize': 'crop', 'wxh': '500x500'}, {'code': 'bigthumb', 'resize': 'crop', 'wxh': '1000x1000'}), upload_to=blog.models.get_file_path)),
                ('title', models.CharField(default='', max_length=255, verbose_name='Оглавление экспоната')),
                ('description', models.TextField(default='', verbose_name='Описание экспоната')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='museumimages', to='blog.Museum', verbose_name='Музей')),
            ],
            options={
                'verbose_name_plural': 'Экспонаты в музее',
                'verbose_name': 'Экспонат в музее',
            },
        ),
    ]
