# Generated by Django 2.0.8 on 2020-02-29 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_museum_museumimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='museumimage',
            name='gallery',
        ),
        migrations.AddField(
            model_name='museumimage',
            name='museum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.Museum', verbose_name='Музей'),
        ),
    ]
